"""Prompt assembly.

PROMPT.md = system wrapper + task template + workspace file listing.

Task templates:
  v5 — byte-exact copies of the pv1105 CLI-wave templates (frozen; checksummed;
       they reference openpyxl-harness tools that coding agents don't have —
       kept for strict-comparability experiments only).
  v6 — the CLI-wave structure/requirements adapted for coding agents.
  v8 — mirror of the v2 GUI prompt with the 132-check rubric embedded
       byte-exact (generated by tools/build_v8_template.py).
  v9 — v8 + the Questions-sheet answer convention (mirror of the v3 GUI
       prompt files; carries the 2026-08 rubric revision, so its rubric
       differs from v8's; generated by tools/build_v9_template.py).
  v10 / v11 — rubric-effect experiment (2026-09-08, frozen: prompt_version
       110/111 have recorded runs): v9 with every rubric-derived passage
       removed (v10); v10 + a pointer to HOUSE_STANDARDS.md, staged into the
       workspace root from prompts/house_standards_v1.md (v11). Generated by
       tools/build_v10_v11_templates.py.
  v12 — benchmark v2 default: v9 + the House Standards directive (mirror of
       the v4 GUI prompt files; rubric byte-identical to v9's). The file it
       names, House_Standards_v1.md, is seeded into starting_files/ by the
       runner (config.TEMPLATE_ATTACHMENTS); generated by
       tools/build_v12_template.py. (Numbered v12 because v10/v11 were
       already recorded by the experiment above.) Superseded as the v2
       default by v13 on 2026-09-10.
  v13 — benchmark v2 default (2026-09-10, the 101-task rerun): the v11 text
       BYTE-IDENTICAL — rubric-free, plus the pointer to HOUSE_STANDARDS.md
       staged into the workspace root — under a new number so the rerun
       cohort never merges with the 111 experiment rows (the judge's
       latest-prompt guard and the manifest key on prompt_version).
       Generated by tools/build_v13_template.py.
  v7 — benchmark v1 default: mirror of the GUI wave's pv9 prompt: the byte-exact pv9 rubric
       preamble (all 17 grading criteria) + the pv9 three-step closing
       (Summary sheet -> model -> Answers sheet) with only harness-necessitated
       edits (workspace/solution.xlsx wording; the "no code interpreter" ban
       becomes "code may build the workbook, but every calculated value must be
       a live Excel formula"). Task-invariant like the GUI wave: one shared
       template for fmwc/modeloff/wsp.

prompt_version (DB column) follows the CLI convention system*100 + template:
system_prompt_coding_v1 + v5 -> 105; + v6 -> 106; + v7 -> 107; + v8 -> 108;
+ v9 -> 109; + v10 -> 110; + v11 -> 111; + v12 -> 112; + v13 -> 113.
"""
import hashlib
import json
import re
from pathlib import Path

from .config import PROMPTS_DIR, RunConfig
from .task_source import TaskSpec

# Frozen pv1105 template checksums (must match cli-agents-master originals).
FROZEN_MD5 = {
    "task_template_fmwc_v5.txt": "801ea39f8d573870ca361b95ff866568",
    "task_template_wsp_v5.txt": "233064b2dd2a38980391e282ef613cc7",
}

# v7 embeds the GUI wave's pv9 rubric preamble byte-exact; guard its first
# 11,971 bytes (md5 of SHARED_rubric_preamble.txt) against accidental edits.
V7_PREAMBLE_MD5 = "7b12403b2dea9ec6d89d333be819ab52"
V7_PREAMBLE_LEN = 11971

# v8 (benchmark v2) embeds the v2 132-check rubric byte-exact from
# gui-agents-master/tasks_configs/prompts_v2/step2_build.txt ("== FULL
# RUBRIC" onward). Regenerate the template with tools/build_v8_template.py;
# never edit the rubric section by hand.
V8_RUBRIC_MD5 = "ff2e3d483da45b722ed1a39db07d1c14"
V8_RUBRIC_LEN = 60470
V8_RUBRIC_MARKER = "== FULL RUBRIC"

# v9 (benchmark v2, Questions-sheet revision) embeds the 132-check rubric
# byte-exact from gui-agents-master/tasks_configs/prompts_v3/step2_build.txt.
# Since the 2026-08 rubric revision (in-place text update from the canonical
# checklist xlsx, Patrick-approved) it deliberately DIFFERS from v8's frozen
# rubric. Regenerate with tools/build_v9_template.py; never edit the rubric
# section by hand.
V9_RUBRIC_MD5 = "b11e174d69a74d239437c572584041ab"
V9_RUBRIC_LEN = 68761

# v12 (benchmark v2, House Standards revision) embeds the rubric byte-exact
# from gui-agents-master/tasks_configs/prompts_v4/step2_build.txt, whose
# rubric is byte-identical to prompts_v3's — hence the same constants as
# v9. Kept as separate names so a future prompts_v4 rubric edit changes
# v12's guard without touching v9's. Regenerate with
# tools/build_v12_template.py; never edit the rubric section by hand.
V12_RUBRIC_MD5 = "b11e174d69a74d239437c572584041ab"
V12_RUBRIC_LEN = 68761

# v10 / v11 (benchmark v2, rubric-effect experiment 2026-09-08): v9 with every
# rubric-derived passage removed (v10), plus a pointer to the house-standards
# file staged into the workspace root (v11). Generated by
# tools/build_v10_v11_templates.py; whole-file md5 pinned below so the text
# recorded under prompt_version 110/111 cannot drift. Filled in once the
# generator has run (see tests/test_smoke.py).
SCRUBBED_MD5 = {
    "task_template_shared_v10.txt": "5b607903172352e82f8fbbac986d96ef",
    "task_template_shared_v11.txt": "008713b35953c2d1356dd81e7f51d4e3",
    # v13 = v11 byte-identical (tools/build_v13_template.py); same pin.
    "task_template_shared_v13.txt": "008713b35953c2d1356dd81e7f51d4e3",
}
SCRUBBED_FORBIDDEN = ("== FULL RUBRIC", "Good:", "Bad:", "rubric", "graded", "grading", "Category weights",
                      "professional-services firm")

# Extra files a template asks the agent to read, staged into the WORKSPACE
# ROOT (not starting_files/) as (source name under prompts/, name in the
# workspace). They are prompt material: snapshotted with the prompts, listed
# under WORKSPACE FILES, hashed into the manifest, and recorded in
# extra_configs.prompt_extras.
TEMPLATE_EXTRAS = {
    "v11": [("house_standards_v1.md", "HOUSE_STANDARDS.md")],
    "v13": [("house_standards_v1.md", "HOUSE_STANDARDS.md")],
}


def _md5(path: Path) -> str:
    return hashlib.md5(path.read_bytes()).hexdigest()


def template_name(task_source: str, version: str) -> str:
    if version in ("v7", "v8", "v9", "v10", "v11", "v12", "v13"):  # task-invariant, like the GUI prompt sets
        return f"task_template_shared_{version}.txt"
    kind = "wsp" if task_source == "wsp" else "fmwc"  # modeloff uses the fmwc template (CLI-wave convention)
    return f"task_template_{kind}_{version}.txt"


def parse_prompt_version(system_name: str, template: str) -> int:
    sys_v = int(re.search(r"_v(\d+)\.txt$", system_name).group(1))
    tpl_v = int(re.search(r"_v(\d+)\.txt$", template).group(1))
    return sys_v * 100 + tpl_v


def prompt_file_paths(cfg: RunConfig, task_source: str) -> tuple[Path, Path]:
    system_path = PROMPTS_DIR / cfg.system_prompt
    tpl_path = PROMPTS_DIR / template_name(task_source, cfg.template_version)
    for p in (system_path, tpl_path):
        if not p.exists():
            raise FileNotFoundError(p)
    if tpl_path.name in FROZEN_MD5 and _md5(tpl_path) != FROZEN_MD5[tpl_path.name]:
        raise RuntimeError(f"{tpl_path.name} no longer matches the frozen pv1105 checksum — do not edit v5 templates")
    if tpl_path.name == "task_template_shared_v7.txt":
        import hashlib as _h
        head = tpl_path.read_bytes()[:V7_PREAMBLE_LEN]
        if _h.md5(head).hexdigest() != V7_PREAMBLE_MD5:
            raise RuntimeError("v7 rubric preamble no longer matches the GUI pv9 original — do not edit the preamble section")
    if tpl_path.name == "task_template_shared_v8.txt":
        import hashlib as _h
        text = tpl_path.read_text()
        idx = text.index(V8_RUBRIC_MARKER)
        rubric = text[idx:idx + V8_RUBRIC_LEN]
        if _h.md5(rubric.encode()).hexdigest() != V8_RUBRIC_MD5:
            raise RuntimeError(
                "v8 rubric section no longer matches the v2 GUI original — "
                "regenerate with tools/build_v8_template.py instead of editing"
            )
    if tpl_path.name == "task_template_shared_v9.txt":
        import hashlib as _h
        text = tpl_path.read_text()
        idx = text.index(V8_RUBRIC_MARKER)
        rubric = text[idx:idx + V9_RUBRIC_LEN]
        if _h.md5(rubric.encode()).hexdigest() != V9_RUBRIC_MD5:
            raise RuntimeError(
                "v9 rubric section no longer matches the v3 GUI original — "
                "regenerate with tools/build_v9_template.py instead of editing"
            )
    if tpl_path.name == "task_template_shared_v12.txt":
        import hashlib as _h
        text = tpl_path.read_text()
        idx = text.index(V8_RUBRIC_MARKER)
        rubric = text[idx:idx + V12_RUBRIC_LEN]
        if _h.md5(rubric.encode()).hexdigest() != V12_RUBRIC_MD5:
            raise RuntimeError(
                "v12 rubric section no longer matches the v4 GUI original — "
                "regenerate with tools/build_v12_template.py instead of editing"
            )
    if tpl_path.name in SCRUBBED_MD5:
        text = tpl_path.read_text()
        hit = [w for w in SCRUBBED_FORBIDDEN if w.lower() in text.lower()]
        if hit:
            raise RuntimeError(f"{tpl_path.name} carries rubric wording {hit} — it must stay rubric-free")
        pin = SCRUBBED_MD5[tpl_path.name]
        if pin is not None and _md5(tpl_path) != pin:
            raise RuntimeError(
                f"{tpl_path.name} no longer matches its pinned md5 — regenerate with "
                "tools/build_v10_v11_templates.py (v10/v11) or tools/build_v13_template.py (v13) "
                "and re-pin, never edit by hand"
            )
    return system_path, tpl_path


def prompt_extra_paths(cfg: RunConfig) -> list[tuple[Path, str]]:
    """(source path, workspace name) for every extra file the template needs."""
    out = []
    for src_name, ws_name in TEMPLATE_EXTRAS.get(cfg.template_version, []):
        src = PROMPTS_DIR / src_name
        if not src.exists():
            raise FileNotFoundError(src)
        out.append((src, ws_name))
    return out


def prompt_extras_provenance(cfg: RunConfig) -> dict:
    """extra_configs.prompt_extras: {workspace name: {source, sha256}} (empty if none)."""
    import hashlib as _h
    return {
        ws_name: {"source": src.name, "sha256": _h.sha256(src.read_bytes()).hexdigest()}
        for src, ws_name in prompt_extra_paths(cfg)
    }


def build_prompt(cfg: RunConfig, spec: TaskSpec, workspace: Path, attempt=None) -> tuple[str, int]:
    """Write PROMPT.md (and any template extras) into the workspace; return
    (prompt_text, prompt_version). When `attempt` is given, extras are hashed
    into its manifest so validation knows they were seeded, not produced."""
    import shutil as _shutil
    system_path, tpl_path = prompt_file_paths(cfg, spec.task_source)
    extras = prompt_extra_paths(cfg)
    for src, ws_name in extras:
        dest = workspace / ws_name
        _shutil.copy2(src, dest)
        if attempt is not None:
            from .workspace import sha256_file
            attempt.manifest[ws_name] = sha256_file(dest)
            (attempt.attempt_dir / "manifest.json").write_text(json.dumps(attempt.manifest, indent=2))
    listing = "\n".join(
        f"- starting_files/{p.name} ({p.stat().st_size:,} bytes)"
        for p in sorted((workspace / "starting_files").iterdir())
    )
    for _src, ws_name in extras:
        listing += f"\n- {ws_name} ({(workspace / ws_name).stat().st_size:,} bytes)"
    prompt = (
        f"{system_path.read_text()}\n"
        f"{tpl_path.read_text()}\n"
        f"WORKSPACE FILES:\n{listing}\n"
    )
    (workspace / "PROMPT.md").write_text(prompt)
    return prompt, parse_prompt_version(system_path.name, tpl_path.name)
