"""Shared prompt versioning config — single source of truth for all batch runners."""
import re
from pathlib import Path

PROMPTS_DIR = Path(__file__).resolve().parent / "prompts"

PROMPT_VERSIONS = {
    "v1": {"system": "system_prompt_v1.txt", "fmwc": "task_template_fmwc_v1.txt", "wsp": "task_template_wsp_v0.txt"},
    "v2": {"system": "system_prompt_v2.txt", "fmwc": "task_template_fmwc_v2.txt", "wsp": "task_template_wsp_v1.txt"},
    "v3": {"system": "system_prompt_v3.txt", "fmwc": "task_template_fmwc_v3.txt", "wsp": "task_template_wsp_v1.txt"},
    "v4": {"system": "system_prompt_v4.txt", "fmwc": "task_template_fmwc_v4.txt", "wsp": "task_template_wsp_v1.txt"},
    "v5": {"system": "system_prompt_v5.txt", "fmwc": "task_template_fmwc_v4.txt", "wsp": "task_template_wsp_v1.txt"},
    "v6": {"system": "system_prompt_v6.txt", "fmwc": "task_template_fmwc_v4.txt", "wsp": "task_template_wsp_v1.txt"},
    "v7": {"system": "system_prompt_v7.txt", "fmwc": "task_template_fmwc_v4.txt", "wsp": "task_template_wsp_v1.txt"},
    "v8": {"system": "system_prompt_v8.txt", "fmwc": "task_template_fmwc_v4.txt", "wsp": "task_template_wsp_v1.txt"},
    "v9": {"system": "system_prompt_v9.txt", "fmwc": "task_template_fmwc_v4.txt", "wsp": "task_template_wsp_v1.txt"},
    "v10": {"system": "system_prompt_v10.txt", "fmwc": "task_template_fmwc_v4.txt", "wsp": "task_template_wsp_v1.txt"},
    # v11: byte-exact prompts of the pv1105 benchmark wave (system v11 + fmwc/wsp
    # templates v5), recovered from S3 task_attempts.prompt_files. Frozen — do not edit.
    "v11": {"system": "system_prompt_v11.txt", "fmwc": "task_template_fmwc_v5.txt", "wsp": "task_template_wsp_v5.txt"},
    # v12: benchmark-v2 prompts — the v11 body with the 132-check/12-category
    # MBABenchV2 rubric (byte-exact from gui-agents prompts_v2/step2_build.txt)
    # and one shared 3-step task template for every task source. Generated by
    # tools/build_v12_prompts.py — regenerate, never hand-edit.
    "v12": {"system": "system_prompt_v12.txt", "fmwc": "task_template_shared_v6.txt", "wsp": "task_template_shared_v6.txt"},
    # v13: v12 + the Questions-sheet answer convention (gui prompts_v3/):
    # the starting workbook's 'Questions' sheet must be preserved in
    # solution.xlsx and answered with live formulas in column B (B2 down).
    # Rubric unchanged from v12. Generated by tools/build_v13_prompts.py —
    # regenerate, never hand-edit. Recorded as prompt_version 1307.
    "v13": {"system": "system_prompt_v13.txt", "fmwc": "task_template_shared_v7.txt", "wsp": "task_template_shared_v7.txt"},
}
DEFAULT_PROMPT_VERSION = "v10"

# Which benchmark's grading rubric each prompt set embeds: v1..v11 carry the
# 17-check/3-category BizbenchV1 rubric, v12/v13 the 132-check/12-category
# MBABenchV2 rubric. auto_batch_runner pairs this against the `benchmark` key
# so v1 tasks run with v1 prompts and v2 tasks with v2 prompts.
V2_RUBRIC_PROMPT_VERSIONS = {"v12", "v13"}


def rubric_for_prompt_version(prompt_ver: str) -> str:
    """Return the benchmark ("v1" | "v2") whose rubric this prompt set embeds."""
    return "v2" if prompt_ver in V2_RUBRIC_PROMPT_VERSIONS else "v1"


def parse_prompt_version(system_path: Path, template_path: Path) -> int:
    """Compute prompt_version: system_v{X} * 100 + template_v{Y}."""
    sys_match = re.search(r'_v(\d+)\.txt$', system_path.name)
    tpl_match = re.search(r'_v(\d+)\.txt$', template_path.name)
    sys_ver = int(sys_match.group(1)) if sys_match else 0
    tpl_ver = int(tpl_match.group(1)) if tpl_match else 0
    return sys_ver * 100 + tpl_ver
